import { Platform } from "@/enumerations/platform";
import { Queue } from "@/enumerations/queue";
import { Rank } from "@/enumerations/Rank";
import { Role } from "@/enumerations/Role";
import { Tier } from "@/enumerations/Tier";
import { Game } from "@/interfaces/game";
import { Participant } from "@/interfaces/participant";
import axios, { AxiosResponse } from "axios";

export async function getHistoryByLoginQueueDateCountRegion(
  login: string,
  queue: Queue,
  dateDebut: number,
  dateFin: number,
  count: number,
  platform: Platform
): Promise<AxiosResponse> {
  return await axios.get(
    `${process.env.VUE_APP_API_URL}/api/game/${login}:${queue}:${dateDebut}:${dateFin}:${count}:${platform}`
  );
}

export async function getParticipantByGame(
  game: Game,
  queue: Queue,
  platform: Platform,
  numberGame: number
): Promise<AxiosResponse> {
  return await axios.post(
    `${process.env.VUE_APP_API_URL}/api/participant/${queue}:${platform}:${numberGame}`,
    game
  );
}

export function getParticipantByPass(): Participant[] {
  return [
    {
      id: "bscbOOk8XYIX_AeLd4R_H-v9T1i2Jj7ncoqukmJF9CIDIauu",
      puuid:
        "TTtJX1u0gsnRJSbgF2iJj6ro_cYA6ejDib89dg5gJanzoEp4l4avpO2WVwng2LyB8CtiWvGUuayWPw",
      teamId: 100,
      win: true,
      totalWin: 4,
      totalLoose: 6,
      championPlayed: "Jax",
      summonerName: "LIDL YSKM",
      teamPosition: Role.TOP,
      tier: Tier.DIAMOND,
      rank: Rank.III,
      leaguePoints: 22,
      totalWinSeason: 96,
      totalLooseSeason: 91,
      calculatedElo: 2122,
      kill: 7,
      death: 2,
      assist: 1,
      kda: 4,
      gold: 10792,
      dmgDealt: 111537,
      dmgTaken: 12860,
      visionScore: 9,
      totalcs: 157,
      longestTimeLiving: 556,
      ally: true,
    },
    {
      id: "OAM0oYwiynDjwloHfw3LtrME-YjNtwHGbGOkyqG5symfAUJR",
      puuid:
        "9MMM-9doz7VFc_3xTOtIMJqohjKo_tAodxVUdImDd7RUO_lcpiYIylRCL36mvJDNORScdVRNSI-TBA",
      teamId: 100,
      win: true,
      totalWin: 7,
      totalLoose: 3,
      championPlayed: "Evelynn",
      summonerName: "Eve on Caffeine",
      teamPosition: Role.JUNGLE,
      tier: Tier.DIAMOND,
      rank: Rank.III,
      leaguePoints: 69,
      totalWinSeason: 91,
      totalLooseSeason: 57,
      calculatedElo: 2169,
      kill: 13,
      death: 1,
      assist: 4,
      kda: 17,
      gold: 10150,
      dmgDealt: 99962,
      dmgTaken: 16052,
      visionScore: 10,
      totalcs: 6,
      longestTimeLiving: 272,
      ally: true,
    },
    {
      id: "XsgaSB9mPy_rtYNsHc7vxggWE8r6sveK_j5tgdqL7bhsxvjK70gNfKdwyA",
      puuid:
        "Si3cKoFJnBvOhjMSa2HLkDKDgSfZ8LMnwsAjxvMchJhFxZbI7JE3EZIiPS2Q8SiICOayjMqhuAVsuA",
      teamId: 100,
      win: true,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "Qiyana",
      summonerName: "Żubr Enjoyer",
      teamPosition: Role.MIDDLE,
      tier: Tier.PLATINUM,
      rank: Rank.I,
      leaguePoints: 89,
      totalWinSeason: 15,
      totalLooseSeason: 13,
      calculatedElo: 1989,
      kill: 4,
      death: 6,
      assist: 3,
      kda: 1.1666666,
      gold: 8009,
      dmgDealt: 68488,
      dmgTaken: 13348,
      visionScore: 14,
      totalcs: 118,
      longestTimeLiving: 206,
      ally: true,
    },
    {
      id: "KO7Yv76O3mv5AQYzo5pxpvAjBq7hWR4l4MEZDnlXp6WTaM4",
      puuid:
        "GXp-fUryMCCqpf-LwtA5md82H4VZJiQtN2nF_i-lsz74oSLgTqkksa1IFhIxnserjVa2LygL3yMSNA",
      teamId: 100,
      win: true,
      totalWin: 5,
      totalLoose: 5,
      championPlayed: "Sivir",
      summonerName: "warm soul",
      teamPosition: Role.BOTTOM,
      tier: Tier.PLATINUM,
      rank: Rank.I,
      leaguePoints: 93,
      totalWinSeason: 29,
      totalLooseSeason: 24,
      calculatedElo: 1993,
      kill: 4,
      death: 1,
      assist: 6,
      kda: 10,
      gold: 8575,
      dmgDealt: 83327,
      dmgTaken: 8123,
      visionScore: 10,
      totalcs: 147,
      longestTimeLiving: 904,
      ally: true,
    },
    {
      id: "PxoFmNWEECs-cZU07WxXqISVjLah_CyTisiCFdvjPsvUGAw",
      puuid:
        "tWinY24dVcDttskhb7rz0369w8UdFE5X-b8iSxmUFke61JrD8OyWo2nuzetQTEdjGmONmbVvdtmFLA",
      teamId: 100,
      win: true,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "LeeSin",
      summonerName: "Léi Feng",
      teamPosition: Role.UTILITY,
      tier: Tier.DIAMOND,
      rank: Rank.IV,
      leaguePoints: 94,
      totalWinSeason: 87,
      totalLooseSeason: 76,
      calculatedElo: 2094,
      kill: 3,
      death: 7,
      assist: 8,
      kda: 1.5714285,
      gold: 6912,
      dmgDealt: 24554,
      dmgTaken: 13476,
      visionScore: 42,
      totalcs: 38,
      longestTimeLiving: 285,
      ally: true,
    },
    {
      id: "beO_vt0BsLM75fEV55sm1w_eHQMu8rHWbRrpDpqR0lK3ELpzAxFkOvc1sQ",
      puuid:
        "5c2rix5uaXfa3NpwZG-_uKmzC_xvBJrkTkLcPxErSVkjDI3V8I0sYGbPmzjxtHKNRSh3bd4arTdJmw",
      teamId: 200,
      win: false,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "Fiora",
      summonerName: "Fleurets",
      teamPosition: Role.TOP,
      tier: Tier.PLATINUM,
      rank: Rank.IV,
      leaguePoints: 44,
      totalWinSeason: 8,
      totalLooseSeason: 10,
      calculatedElo: 1644,
      kill: 0,
      death: 7,
      assist: 0,
      kda: 0,
      gold: 5076,
      dmgDealt: 46166,
      dmgTaken: 13875,
      visionScore: 16,
      totalcs: 106,
      longestTimeLiving: 218,
      ally: false,
    },
    {
      id: "67NxT_NeeoltzDcCmBxeH5dA1NU0X6nFj4s6Yy4RoUvzcUnA",
      puuid:
        "9hJcyWJj1j-gusOHwhKEt9l3xL-toMbvajlwwtvP0JvqJ10LspGos26ZUKITViVfn2sI13Lu6d5_-Q",
      teamId: 200,
      win: false,
      totalWin: 3,
      totalLoose: 7,
      championPlayed: "Sylas",
      summonerName: "TheOneSolution",
      teamPosition: Role.JUNGLE,
      tier: Tier.DIAMOND,
      rank: Rank.IV,
      leaguePoints: 10,
      totalWinSeason: 12,
      totalLooseSeason: 23,
      calculatedElo: 2010,
      kill: 6,
      death: 4,
      assist: 1,
      kda: 1.75,
      gold: 8724,
      dmgDealt: 110750,
      dmgTaken: 24102,
      visionScore: 11,
      totalcs: 10,
      longestTimeLiving: 524,
      ally: false,
    },
    {
      id: "4kfdM4FlmKOIj4qgCMZ37J4Fp5dSPt_fxYeF9ax8lWgwPIE",
      puuid:
        "PNyvjOf8MkUfZBP94t2_8IROcfVTbIv7xf1jcf1PMrLR9yGeWNRLIhNPPGMa53sG7AuZBgeC4ZI21w",
      teamId: 200,
      win: false,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "Talon",
      summonerName: "Haru Hikigaya",
      teamPosition: Role.MIDDLE,
      tier: Tier.DIAMOND,
      rank: Rank.IV,
      leaguePoints: 11,
      totalWinSeason: 56,
      totalLooseSeason: 48,
      calculatedElo: 2011,
      kill: 3,
      death: 7,
      assist: 1,
      kda: 0.5714286,
      gold: 6762,
      dmgDealt: 67573,
      dmgTaken: 14091,
      visionScore: 7,
      totalcs: 113,
      longestTimeLiving: 379,
      ally: false,
    },
    {
      id: "MnV8MkcTu1baABouc9z6AhWOgvKExm1Xxb6-s7AHOm5NSyE",
      puuid:
        "tV1W3pU190MWOZmpZ4t2tIHIDdJft9mLrjBKMVJDqTLUG7YG3KGF_QLzxwirwO1XkOlMsBPpik0JkQ",
      teamId: 200,
      win: false,
      totalWin: 4,
      totalLoose: 6,
      championPlayed: "Varus",
      summonerName: "Ascha",
      teamPosition: Role.BOTTOM,
      tier: Tier.DIAMOND,
      rank: Rank.III,
      leaguePoints: 58,
      totalWinSeason: 116,
      totalLooseSeason: 97,
      calculatedElo: 2158,
      kill: 5,
      death: 5,
      assist: 3,
      kda: 1.6,
      gold: 7061,
      dmgDealt: 53963,
      dmgTaken: 11008,
      visionScore: 15,
      totalcs: 126,
      longestTimeLiving: 455,
      ally: false,
    },
    {
      id: "F3q7fXc_CZ5j5vvrvJzfsC1NuQhwYMYBttHb114Od2PN5Ow",
      puuid:
        "X0-3TOjFhF28IXynkDW2_7JceJQNpC3xt6ezacBc3wzL0WaUPYFyIA2TJijMauoFsu5DvSIJQ4wO4w",
      teamId: 200,
      win: false,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "Lux",
      summonerName: "BLACKPINK Rosé",
      teamPosition: Role.UTILITY,
      tier: Tier.DIAMOND,
      rank: Rank.IV,
      leaguePoints: 75,
      totalWinSeason: 56,
      totalLooseSeason: 50,
      calculatedElo: 2075,
      kill: 2,
      death: 8,
      assist: 7,
      kda: 1.125,
      gold: 5525,
      dmgDealt: 23918,
      dmgTaken: 12605,
      visionScore: 17,
      totalcs: 13,
      longestTimeLiving: 302,
      ally: false,
    },
  ];
}
