import { Platform } from "@/enumerations/platform";
import { Queue } from "@/enumerations/queue";
import { Rank } from "@/enumerations/Rank";
import { Role } from "@/enumerations/Role";
import { Tier } from "@/enumerations/Tier";
import { Game } from "@/interfaces/game";
import { Participant } from "@/interfaces/participant";
import axios, { AxiosResponse } from "axios";

const config = {
  headers: {
    "Access-Control-Allow-Origin": "*",
  },
};

export async function getHistoryByLoginQueueDateCountRegion(
  login: string,
  queue: Queue,
  dateDebut: number,
  dateFin: number,
  count: number,
  platform: Platform
): Promise<AxiosResponse> {
  return await axios.get(
    `${process.env.VUE_APP_API_URL}/api/game/${login}:${queue}:${dateDebut}:${dateFin}:${count}:${platform}`,
    config
  );
}

export async function fillParticipantByGame(
  game: Game,
  queue: Queue,
  platform: Platform,
  numberGame: number,
  participantId: string
): Promise<AxiosResponse> {
  return await axios.post(
    `${process.env.VUE_APP_API_URL}/api/participant/${queue}:${platform}:${numberGame}:${participantId}`,
    game,
    config
  );
}

export function getParticipantByPass(): Participant[] {
  return [
    {
      id: "FewS5GNtc7HxBtYk8VCCkVUqqhHjLYYvvL-dNdGUHz1pctcI",
      puuid:
        "wHSJ5_eBocWrHkG8qN6QY1dnOs0EAMSnnVjhNt5BM1GkkV6SyLr9frIsSsTJLe6xVyVlVZ1y0tCkIw",
      teamId: 100,
      win: true,
      totalWin: 5,
      totalLoose: 5,
      championPlayed: "Fiora",
      summonerName: "ZZcro",
      teamPosition: Role.TOP,
      tier: Tier.MASTER,
      rank: Rank.I,
      leaguePoints: 292,
      totalWinSeason: 62,
      totalLooseSeason: 45,
      calculatedElo: 2692,
      kill: 6,
      death: 7,
      assist: 14,
      kda: 2.857143,
      gold: 13112,
      dmgDealt: 143680,
      dmgTaken: 44510,
      visionScore: 27,
      totalcs: 166,
      longestTimeLiving: 470,
      ally: false,
    },
    {
      id: "9h6ooO1pF4ct085JRE4cP2xwznmuJ0511JeMzeBaxBtuItg",
      puuid:
        "37bWEoXDsx9ByGE7swbWlnNCIEepiRL3lrDAUTt0UMd3gSOgD2CtDHvvKFc10pTU6niHmD6hHqE6cg",
      teamId: 100,
      win: true,
      totalWin: 4,
      totalLoose: 6,
      championPlayed: "Diana",
      summonerName: "KikiiEnClaket",
      teamPosition: Role.JUNGLE,
      tier: Tier.GRANDMASTER,
      rank: Rank.I,
      leaguePoints: 558,
      totalWinSeason: 145,
      totalLooseSeason: 123,
      calculatedElo: 2958,
      kill: 9,
      death: 8,
      assist: 24,
      kda: 4.125,
      gold: 16516,
      dmgDealt: 326879,
      dmgTaken: 43027,
      visionScore: 31,
      totalcs: 58,
      longestTimeLiving: 664,
      ally: false,
    },
    {
      id: "kVGWP2Y6xO4rWMk4Cowlj8SyCf__ff-rF4qAVhDlbwpnkRGp9yU_qq3F5g",
      puuid:
        "VOAPizfrCC7rpMWpuN70FggCu-DBTxY2OPgnyjTutHhEPPpmEb5YzJ8l38ypU6PbizkhiObt9aC0Vg",
      teamId: 100,
      win: true,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "Akali",
      summonerName: "Kidyu",
      teamPosition: Role.MIDDLE,
      tier: Tier.MASTER,
      rank: Rank.I,
      leaguePoints: 128,
      totalWinSeason: 30,
      totalLooseSeason: 18,
      calculatedElo: 2528,
      kill: 20,
      death: 5,
      assist: 10,
      kda: 6,
      gold: 17831,
      dmgDealt: 153129,
      dmgTaken: 32705,
      visionScore: 40,
      totalcs: 174,
      longestTimeLiving: 1026,
      ally: false,
    },
    {
      id: "871monm5uiur81PJcJ7q7ozK77IoXnKh5FGzlyUTu7dUN9J3",
      puuid:
        "KFZ7flHeN_Ywqoteq3FJyPNuCgB5uJyCRDaudc9ONsrzv-XJLRZ4QVwWx69ijlhW-SLsxp7HkCauVg",
      teamId: 100,
      win: true,
      totalWin: 5,
      totalLoose: 5,
      championPlayed: "Draven",
      summonerName: "bugatti twitch1",
      teamPosition: Role.BOTTOM,
      tier: Tier.GRANDMASTER,
      rank: Rank.I,
      leaguePoints: 561,
      totalWinSeason: 135,
      totalLooseSeason: 127,
      calculatedElo: 2961,
      kill: 15,
      death: 9,
      assist: 17,
      kda: 3.5555556,
      gold: 23049,
      dmgDealt: 349942,
      dmgTaken: 31594,
      visionScore: 38,
      totalcs: 232,
      longestTimeLiving: 358,
      ally: false,
    },
    {
      id: "_H-68Vb36Hbz4gHmgAdBSj6szt_Vjqglill_9sJIk1JXUM5avw6J9FRftQ",
      puuid:
        "oK4CL2GhaERmltiQ3N-IlOeVnO2qaYn3yYzhaM0EheSJup5EJfNrjSyYOecXQOB8GxG4n8kqCWEzOA",
      teamId: 100,
      win: true,
      totalWin: 5,
      totalLoose: 5,
      championPlayed: "Leona",
      summonerName: "RogueTheWallaby",
      teamPosition: Role.UTILITY,
      tier: Tier.DIAMOND,
      rank: Rank.I,
      leaguePoints: 100,
      totalWinSeason: 17,
      totalLooseSeason: 12,
      calculatedElo: 2400,
      kill: 3,
      death: 8,
      assist: 31,
      kda: 4.25,
      gold: 11422,
      dmgDealt: 33792,
      dmgTaken: 41103,
      visionScore: 80,
      totalcs: 35,
      longestTimeLiving: 421,
      ally: false,
    },
    {
      id: "C2GTC-BUjW7zZcbCMmHkIaiqpnQPbj7fjLBl3KHscFI3pQU",
      puuid:
        "RXdbqmY5z8FpH-ND5vKvukiz36Xlbw865eTANuqATB29kCyLcFqn_YRH0CAkG8ZZ6n09-Pnj9IucAQ",
      teamId: 200,
      win: false,
      totalWin: 2,
      totalLoose: 8,
      championPlayed: "Sett",
      summonerName: "e ti de quen ves",
      teamPosition: Role.TOP,
      tier: Tier.GRANDMASTER,
      rank: Rank.I,
      leaguePoints: 631,
      totalWinSeason: 138,
      totalLooseSeason: 129,
      calculatedElo: 3031,
      kill: 7,
      death: 13,
      assist: 6,
      kda: 1,
      gold: 15708,
      dmgDealt: 209429,
      dmgTaken: 56616,
      visionScore: 41,
      totalcs: 213,
      longestTimeLiving: 484,
      ally: true,
    },
    {
      id: "VRlc7mrSidasjYPTFUqHc3cnM9KLYpEm5Itb4rB0KC3lTjw",
      puuid:
        "K2sodtYFBBwwcsc4Bq8pfnjRXWuYtWuj5AiXKINRWRcdmcHQxPUvb7xnpE3-OH3qr3Iyg1KcXF9PNA",
      teamId: 200,
      win: false,
      totalWin: 5,
      totalLoose: 5,
      championPlayed: "Zac",
      summonerName: "PatateVolante",
      teamPosition: Role.JUNGLE,
      tier: Tier.DIAMOND,
      rank: Rank.I,
      leaguePoints: 95,
      totalWinSeason: 22,
      totalLooseSeason: 21,
      calculatedElo: 2395,
      kill: 8,
      death: 8,
      assist: 17,
      kda: 3.125,
      gold: 13026,
      dmgDealt: 191067,
      dmgTaken: 69291,
      visionScore: 28,
      totalcs: 30,
      longestTimeLiving: 416,
      ally: true,
    },
    {
      id: "tXzHDeKwsjm9xjip3Vyi26YRojdpMRO9mMU2T51sxG-vd3FCRpKz-Lghuw",
      puuid:
        "gIkqS1cXu-XFqms3z4o9fmcIU8WcV78n2CZMPE2xnF0NxmVfPSAF6b8UE1365qwJ-T_GMumoekfkNA",
      teamId: 200,
      win: false,
      totalWin: 6,
      totalLoose: 4,
      championPlayed: "Orianna",
      summonerName: "Love and hatred",
      teamPosition: Role.MIDDLE,
      tier: Tier.MASTER,
      rank: Rank.I,
      leaguePoints: 174,
      totalWinSeason: 44,
      totalLooseSeason: 32,
      calculatedElo: 2574,
      kill: 5,
      death: 9,
      assist: 13,
      kda: 2,
      gold: 14798,
      dmgDealt: 219788,
      dmgTaken: 25521,
      visionScore: 25,
      totalcs: 264,
      longestTimeLiving: 467,
      ally: true,
    },
    {
      id: "ezmJyf5R-ilOHAuC4xL3ujQK459P8ZKSUZODpgpKvar8l7I",
      puuid:
        "ECc762E6kdUrhiL4df5_T5yJCfDzgfIQtFCi2ssFwjl0LKTMqkkMpbb_TVQhXcSW3ppUvwlrwDvI0w",
      teamId: 200,
      win: false,
      totalWin: 4,
      totalLoose: 6,
      championPlayed: "Varus",
      summonerName: "CHAP PXXL",
      teamPosition: Role.BOTTOM,
      tier: Tier.GRANDMASTER,
      rank: Rank.I,
      leaguePoints: 619,
      totalWinSeason: 174,
      totalLooseSeason: 158,
      calculatedElo: 3019,
      kill: 15,
      death: 13,
      assist: 12,
      kda: 2.0769231,
      gold: 16887,
      dmgDealt: 207049,
      dmgTaken: 43825,
      visionScore: 32,
      totalcs: 211,
      longestTimeLiving: 291,
      ally: true,
    },
    {
      id: "NFOOmUaOTEjVFN--JpjtLST4o6i1MPjEl4JwGGzzaflUHtY",
      puuid:
        "tSy8c8VNst1aICyjWUmyDXLPxeZ2Dw97KhKnhfJu4EAI9aIlUMv_6nsBAGMSUmoYGbA9jPLth5sovA",
      teamId: 200,
      win: false,
      totalWin: 7,
      totalLoose: 3,
      championPlayed: "Janna",
      summonerName: "Tévaa",
      teamPosition: Role.UTILITY,
      tier: Tier.MASTER,
      rank: Rank.I,
      leaguePoints: 379,
      totalWinSeason: 74,
      totalLooseSeason: 62,
      calculatedElo: 2779,
      kill: 2,
      death: 10,
      assist: 27,
      kda: 2.9,
      gold: 10288,
      dmgDealt: 11669,
      dmgTaken: 30177,
      visionScore: 98,
      totalcs: 20,
      longestTimeLiving: 406,
      ally: true,
    },
  ];
}
