export enum Tier {
  IRON = "IRON",
  BRONZE = "BRONZE",
  SIVLER = "SIVLER",
  GOLD = "GOLD",
  PLATINUM = "PLATINUM",
  DIAMOND = "DIAMOND",
  MASTER = "MASTER",
  GRANDMASTER = "GRANDMASTER",
  CHALLENGER = "CHALLENGER",
}
